[serieson_event ]
title = "[시리즈온] 이벤트"
url = "https://serieson.naver.com/movie/eventList.nhn"
entrySelector = "ul li.event:not(:first-child)"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"
