[magazines]
title = "VIBE ─ 매거진"
url = "https://vibe.naver.com/magazines"
entrySelector = "ul.mag_list li.list_item"
titleSelector = "div.info a.title"
linkSelector = "div.thumb_area a.link"
contentSelector = "div.info div.sub span.item"
imageSelector = "div.thumb img.v-lazy-image.v-lazy-image-loaded"
waitUntil = "networkidle"
