[nestnada_inpock]
title = "네스트나다 ─ 인포크링크"
url = "https://link.inpock.co.kr/nestnada"
entrySelector = "div.links a"
titleSelector = "div.link-meta p[class='inpock-typography paragraph-2 titleClass title']"
linkSelector = "a"
imageSelector = "div[class='link gtm-link-click-visitor'] div.image"
waitUntil = "networkidle"

[nestnada]
title = "네스트나다 ─ 인포크링크"
url = "https://link.inpock.co.kr/nestnada"
entrySelector = "//html/body/div/div/div/div/div/div/a/div"
titleSelector = "//div[2]/p[1]"
linkSelector = "//div[2]/p[1]"
