[ticketlink]
title = "티켓링크"
url = "http://www.ticketlink.co.kr/help/notice"
entrySelector = "tbody[id='nTableBody'] tr"
titleSelector = "td.tl.p_reative > a"
linkSelector = "td a"
contentSelector = "td[class='open_info']"
waitForSelector = ".basic_tbl"
