[bbc_korean_popular]
title = "BBC News 코리아 ─ TOP 뉴스"
url = "https://www.bbc.com/korean/popular/read"
entrySelector = "ol.e713knt2.bbc-zztj29.e57qer20 li"
titleSelector = "a.bbc-bta7jm.emesykt4"
linkSelector = "a.bbc-bta7jm.emesykt4"
contentSelector = "span.bbc-1kpt1ox.erh4ywh0"
waitUntil = "networkidle"
