[beyondlive_notice]
title = "Beyond LIVE ─ 공지사항"
url = "https://beyondlive.com/notice?lang=ko"
entrySelector = "ul.notice-list li.notice-list__item"
titleSelector = "span.notice-list__title.notice-list__title"
linkSelector = "a.notice-list__link"
dateSelector = "notice-list__date"
dateFormat = "yyyy. MM. dd"
contentSelector = "span.notice-list__date"
waitUntil = "networkidle"

[bbc_korean_popular]
title = "BBC News 코리아 ─ TOP 뉴스"
url = "https://www.bbc.com/korean/popular/read"
entrySelector = "ol.e713knt2.bbc-zztj29.e57qer20 li"
titleSelector = "a.bbc-bta7jm.emesykt4"
linkSelector = "a.bbc-bta7jm.emesykt4"
waitUntil = "networkidle"
