[clubevans]
title = "클럽 에반스 ─ SCHEDULE"
url = "http://www.clubevans.com/bbs/board.php?bo_table=TODAYS_LIVE"
entrySelector = "center[id='G4_LIST'] table tr:nth-child(n+3) td"
titleSelector = "div:nth-child(2) a"
linkSelector = "div:nth-child(2) a"
waitUntil = "networkidle"

[m_cine21_news]
title = "씨네21 모바일 ─ 뉴스"
url = "http://m.cine21.com/news/lists/?s=0"
entrySelector = "ul.lst_top2 li"
titleSelector = "div.tit"
linkSelector = "a"
contentSelector = "div.category"
imageSelector = "div.thub img"
waitUntil = "networkidle"
