[vscreen_notice]
title = "V SCREEN ─ Notice"
url = "https://www.vlive.tv/channel/C956BB/board/1732"
entrySelector = "//html/body/div/div/div/div[2]/div[3]/div[2]/ul/li"
titleSelector = "//a/div/div[1]/div[1]/strong"
linkSelector = "//a"
contentSelector = "//div[1]/div/a/div[2]/div[1]/em"
dataSelector = "//div[1]/div/a/div[2]/div[2]/div/span"
dataFormat = "M.d."
waitUntil = "networkidle"
onFail = "stale"
