[vibe_onstage]
title = "VIBE ─ 온스테이지"
url = "https://vibe.naver.com/onstage/season/2"
entrySelector = "div.section_intro div.video_info"
titleSelector = "div.main_text.custom_font.scrollmagic.animated a.title"
linkSelector = "div.button_area a.link_detail.scrollmagic.animated"
contentSelector = "div.main_text.custom_font.scrollmagic.animated p.desc"
waitForSelector = "div.video_info"

[jisike]
title = "지식채널e"
url = "https://home.ebs.co.kr/jisike/replayList"
entrySelector = "ul.list li"
titleSelector = "p.tit"
linkSelector = "p.pic a"
contentSelector = "p.con"
