[imbc_govideo]
title = "출발! 비디오 여행 ─ 스페셜영상"
url = "https://m.imbc.com/VOD/SketchList/1000827100000100000?type=3"
entrySelector = "div.documentation ul.wrap-item li.item"
titleSelector = "div.title span.tit"
linkSelector = "a"
contentSelector = "div.meta span.date"
imageSelector = "div.w_photo img"
waitUntil = "networkidle"
