[khan_factcheck]
title = "경향신문 ─ 연재 ─ 팩트체크"
url = "https://www.khan.co.kr/series/articles/aj165"
entrySelector = "div.main-list-wrap ul.df-list li"
titleSelector = "h2.tit a"
linkSelector = "h2.tit a"
contentSelector = "span.lead a.line_clamp2"
dateSelector = "span.byline"
dateFormat = "yyyy.MM.dd hh:mm"
imageSelector = "div.thumb picture img"
waitUntil = "networkidle"
