[gaonchart_notice]
title = "가온차트 ─ 공지사항"
url = "http://www.gaonchart.co.kr/main/section/notice/list.gaon"
entrySelector = "table tbody tr"
titleSelector = "td.al"
linkSelector = "td.al a"
contentSelector = "td:nth-child(3)"
