[funtenna_story]
title = "펀샵 ─ 펀테나 ─ 스토리"
url = "https://www.funshop.co.kr/Story/StoryList#page=1"
entrySelector = "div.story_list ul li"
titleSelector = "dl dt"
linkSelector = "a.cover"
contentSelector = "dd p.text"
imageSelector = "img.item.lazy"
waitForSelector = "div.story_list ul li"
onFail = "stale"
