[cjazit]
title = "CJ문화재단 ─ 공연예매"
url = "https://www.cjazit.org/cjazit/book/list"
entrySelector = "div.list div.item"
titleSelector = "h3.item-heading"
linkSelector = "div.item-body a"
contentSelector = "div.item-details"
imageSelector = "div.item-thumb img"
waitUntil = "networkidle"
