[wwit]
title = "WWIT"
url = "https://wwit.design/"
entrySelector = "h2.c-post-card__title"
titleSelector = "a.c-post-card__title-link"
linkSelector = "h2 a"
contentSelector = "div.c-post-card__meta"
imageSelector = "img.c-post-card__image.js-fadein.is-inview:nth-child(1)"
waitUntil = "networkidle"
