[tech_article]
title = "블로터 ─ 테크"
url = "https://www.bloter.net/section?id=sectionTech"
entrySelector = "div.box.section_tech_newslist ul.list li.article"
titleSelector = "a.link h4.title"
linkSelector = "a.list"
contentSelector = "div.info"
imageSelector = "div.thumb div.background.zoom img"
waitUntil = "networkidle"
