[jobplanet_news]
title = "잡플래닛 ─ 뉴스"
url = "https://www.jobplanet.co.kr/contents/news"
entrySelector = "ul li.story_contents_item_ty"
titleSelector = "h2.title"
linkSelector = "a"
contentSelector = "p.desc"
imageSelector = "div.img_thumb img"
waitUntil = "networkidle"
