[today]
title = "alookso ─ 투데이"
url = "https://alook.so/"
entrySelector = "section:nth-child(1) > div:nth-child(3) > div.py-8.space-y-4 > div[class='flex items-center space-x-4']"
titleSelector = "div[class='flex flex-col justify-between h-32'] > div[class='mb-1 space-y-2'] > div[class='text-lg font-semibold text-gray-800 break-all line-clamp-2'] a"
linkSelector = "a"
contentSelector = "div[class='flex flex-col justify-between h-32'] > div[class='mb-1 space-y-2'] > div[class='hidden text-sm font-normal text-gray-400 md:line-clamp-2 md:block'] a"
imageSelector = "a > div[class='w-48 h-32'] > img"
waitUntil = "networkidle"
onFail = "stale"
