[cine21_playing]
title = "씨네21 ─ 영화 ─ 현재 상영중"
url = "http://www.cine21.com/movie/lists/playing"
entrySelector = "ul.mov_info_list li.mov_info_li"
titleSelector = "div.over span.tit"
linkSelector = "a"
contentSelector = "div.over span.open_date"
imageSelector = "a img.thumb"
waitUntil = "networkidle"
