[vibe_onstage]
title = "VIBE ─ 온스테이지"
url = "https://vibe.naver.com/onstage/season/2"
entrySelector = "div.section_intro div.video_info"
titleSelector = "a.title"
linkSelector = "div.button_area a.link_detail.scrollmagic.animated"
waitUntil = "networkidle"
