[kakao_contentv_maxmovie]
title = "맥스무비 ─ 카카오 콘텐츠뷰"
url = "https://content.v.daum.net/2249/contents"
entrySelector = "ul.list_column li"
titleSelector = "strong.tit_item"
linkSelector = "a.link_column"
imageSelector = "img.thumb_g"
waitUntil = "networkidle"
