[investing_latest]
title = "더밀크 ─ Investing ─ 최신기사"
url = "https://themiilk.com/investing/latest"
entrySelector = "div.content-wrapper ul.list li.item"
titleSelector = "h2.title.label-middle-title.bold.ellipsis.two"
linkSelector = "div.image-wrapper.remove-line-height a"
contentSelector = "p.description.label-middle-description.ellipsis.three"
imageSelector = "div.image-wrapper.remove-line-height a div.image-box"
waitUntil = "networkidle"
