[m_hyangmusic_precontract]
title = "모바일 향뮤직 ─ 예약 음반"
url = "http://hyangmusic.com/m/?mcid=contents&mpid=precontract"
entrySelector = "div[style='background-color:#fff;width:100%;height:auto;max-heightx:100%;margin:0px;padding:11px;margin-topx:5px;']"
titleSelector = "div:nth-child(2) > div:nth-child(2)"
linkSelector = "div a"
contentSelector = "div:nth-child(2) > div.ellipsis.search_link > span"
imageSelector = "img.img_thmbnail.img_border.lazy"
waitUntil = "networkidle"
