[today_more]
title = "alookso ─ 투데이"
url = "https://alook.so/"
entrySelector = "section:nth-child(2) > div.hidden.md:block > div > div.flex.items-center.space-x-4"
titleSelector = "div.mb-1.space-y-2 > div.text-lg.font-semibold.text-gray-800.break-all.line-clamp-2 > a"
linkSelector = "a"
contentSelector = "div.mb-1.space-y-2 > div.hidden.text-sm.font-normal.text-gray-400.md:line-clamp-2.md:block > a"
waitUntil = "networkidle"
