[prismhall]
title = "프리즘홀"
url = "https://www.kamimusic.com/tobe"
entrySelector = "//div[@class='info-element-text']"
titleSelector = "//div[@class='info-member info-element-title']/span"
linkSelector = "a"
contentSelector = "//div[@class='info-member info-element-description']/span"
imageSelector = "//div[1]/picture/img"
waitUntil = "networkidle"
