[daum_entertain_news_drama]
title = "다음 연예 ─ 뉴스 ─ 드라마"
url = "https://entertain.daum.net/news/drama"
entrySelector = "//ul[@class='list_news']/li"
titleSelector = "//div/strong"
linkSelector = "//div/strong/a[@class='link_txt']"
contentSelector = "//div/p[@class='desc_thumb']"
waitUntil = "networkidle"
onFail = "stale"
