[disquiet]
title = "Disquiet"
url = "https://disquiet.io/"
entrySelector = "div.sc-gVgnHT.bfDGHw div.sc-XhUPp.kiNLFp"
titleSelector = "h3.title"
linkSelector = "div.sc-fbNXWD.emHwAg"
contentSelector = "div.sc-gsxnyZ.gILzWP"
waitUntil = "networkidle"
