[disquiet_product]
title = "Disquiet ─ 프로덕트"
url = "https://disquiet.io/?sort=recent&type=product"
entrySelector = "div[class*='clickable']"
titleSelector = "div.card-title"
linkSelector = "*"
contentSelector = "div.sc-jEUCeg.fklEVh div.sc-bOdqNl.jzLQXV"
waitUntil = "networkidle"
