[new]
title = "GeekNews ─ 최신글"
url = "https://news.hada.io/new"
entrySelector = "div.topic_row"
titleSelector = "div.topic_row div.topictitle"
linkSelector = "div.topic_row div.topicdesc a"
waitUntil = "networkidle"

[show]
title = "GeekNews Show"
url = "https://news.hada.io/show"
entrySelector = "div.topic_row"
titleSelector = "div.topictitle"
linkSelector = "div.topictitle a"
contentSelector = "div.topicdesc a"
waitUntil = "networkidle"

