[vibe_recent]
title = "VIBE ─ 온스테이지"
url = "https://vibe.naver.com/onstage/season/2"
entrySelector = "//html/body/div/div/div[3]/div/div/div[2]"
titleSelector = "//div/div[1]/a"
linkSelector = "//div/div[1]/a"
contentSelector = "//div/div[1]/p"
waitForSelector = ".video_info"
onFail = "stale"

[showdeerocks]
title = "쇼디락스"
url = "http://showdeerocks.info/article.html"
entrySelector = "//html/body/div"
titleSelector = "//span"
linkSelector = "//span[@class='Link']/a"
waitUntil = "networkidle"
