[gurumare]
title = "구름아래소극장 ─ 공연안내"
url = "http://gurumare.co.kr/show"
entrySelector = "div.col-xs-6.col-lg-3.col-md-6"
titleSelector = "div.col-xs-6.col-lg-3.col-md-6"
linkSelector = "div a"
imageSelector = "a img"
waitUntil = "networkidle"
