[interview]
title = "POCLANOS ─ Interview"
url = "https://poclanos.com/category/interview/"
entrySelector = "header.entry-header"
titleSelector = "h2.entry-title a"
linkSelector = "h2.entry-title a"
contentSelector = "div.entry-content"
imageSelector = "a.post-thumbnail img "
waitUntil = "networkidle"
