[disquiet_product]
title = "Disquiet ─ 프로덕트"
url = "https://disquiet.io/?sort=recent&type=product"
entrySelector = "//html/body/div[3]/div[2]/div[2]/div[6]/div/div[2]/div/div/div[2]"
titleSelector = "div.card-title"
linkSelector = "*"
contentSelector = "div.sc-jEUCeg.fklEVh div.sc-bOdqNl.jzLQXV"
waitUntil = "networkidle"
