[vibe_onstage]
title = "VIBE ─ 온스테이지"
url = "https://vibe.naver.com/onstage/season/2"
entrySelector = "div.main_text.custom_font.scrollmagic.animated"
titleSelector = "a.title"
linkSelector = "a"
waitUntil = "networkidle"
