[gaonchart_certification]
title = "가온차트 ─ 인증"
url = "http://www.gaonchart.co.kr/main/section/certification/list.gaon"
entrySelector = "div.chart tbody tr"
titleSelector = "td.title"
linkSelector = "td:nth-child(2) > img"
contentSelector = "td:nth-child(4)"
imageSelector = "td:nth-child(1) > img"
waitUntil = "networkidle"
