[news]
title = "무신사 ─ 패션 뉴스"
url = "https://www.musinsa.com/mz/news"
entrySelector = "ul.scmenu-list.news li"
titleSelector = "div.info h3 a:nth-child(2)"
linkSelector = "div.info h3 a:nth-child(2)"
contentSelector = "p.context"
imageSelector = "span.imgBox img"
waitForSelector = "ul.scmenu-list.news li"
