[originals]
title = "얼룩소 ─ 오리지널"
url = "https://alook.so/originals"
entrySelector = "div.flex.flex-col.break-words.min-w-0.bg-white"
titleSelector = "h5[data-qa='post-title'] a"
linkSelector = "h5[data-qa='post-title'] a"
contentSelector = "h6 a.trix-content-post-partial div.trix-content.line-clamp-5"
imageSelector = "div.relative.z-0.flex.-space-x-4 a:nth-child(1) img"
waitUntil = "networkidle"
