[daum_entertain_news_drama]
title = "다음 연예 ─ 뉴스 ─ 드라마"
url = "https://entertain.daum.net/news/drama"
entrySelector = "//html/body/div/div/div/div/div/ul/li/div/strong"
titleSelector = "//a[1]"
linkSelector = "//a[1]"
contentSelector = "//span[1]"
waitUntil = "networkidle"
