[alookso_test]
title = "테스트"
url = "https://alook.so/users/8Ogtna"
entrySelector = "[id^=post_]"
titleSelector = ".post-title"
linkSelector = ".post-title a"
contentSelector = ".trix-content"
waitUntil = "networkidle"
filter = "relative pb-6"
onFail = "stale"
