[independentfilm]
title = "독립영화관 ─ 네이버TV"
url = "https://tv.naver.com/kbs.independentfilm/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dl.cds_info dt.title tooltip"
linkSelector = "div.cds_type a.cds_thm"
imageSelector = "div.cds_type a.cds_thm"
contentSelector = "span.tm_b"
waitForSelector = "div[class^='cds _MM_CARD']"
