[musinsa_magazine_news]
title = "무신사 ─ 패션 뉴스"
url = "https://magazine.musinsa.com/?m=news"
entrySelector = "ul.news-article-list.article-list.list li.listItem"
titleSelector = "p.title a"
linkSelector = "p.title a"
contentSelector = "div.description p"
imageSelector = "div.articleImg img"
waitForSelector = "ul.news-article-list.article-list.list li.listItem"
onFail = "stale"
