[snufactcheck]
title = "SNU 팩트체크"
url = "http://factcheck.snu.ac.kr/v2/facts"
entrySelector = "ul li.fcItem_wrap_li"
titleSelector = "div.prg.fcItem_li p:nth-child(3)"
linkSelector = "div.prg.fcItem_li > p:nth-child(3) a"
contentSelector = "div.meter-label"
waitUntil = "networkidle"
