[vstore_membership]
title = "V LIVE ─ MEMBERSHIP"
url = "https://www.vlive.tv/vstore/membership"
entrySelector = "ul.channel_fanship_list._mem_list li"
titleSelector = "strong.title"
linkSelector = "a"
contentSelector = "div.info_area em"
imageSelector = "div.thumb_area img"
waitUntil = "networkidle"
