[newneek]
title = "뉴닉 ─ 전체"
url = "https://newneek.co/"
entrySelector = "section.sc-bdnxRM.jvCTkj.home-recent div.posts a"
titleSelector = "div.card-inner div.card-body h3.card-title"
linkSelector = "*"
contentSelector = "div.card-inner div.card-body p.card-text"
dateSelector = "div.card-inner div.card-body time.card-date"
dateFormat = "yyyy/MM/dd"
imageSelector = "div.card-inner figure.card-thumbnail"
waitUntil = "networkidle"
