[show]
title = "GeekNews Show"
url = "https://news.hada.io/show"
entrySelector = "div.topic_row"
titleSelector = "div.topictitle"
linkSelector = "div.topictitle a"
contentSelector = "div.topicdesc a"
waitUntil = "networkidle"
