[funshop_funtenna]
title = "펀샵 ─ 펀테나"
url = "https://www.funshop.co.kr/Story/FuntennaList"
entrySelector = "ul[id='list'] li"
titleSelector = "dl dt"
linkSelector = "a"
contentSelector = "dd p.text"
imageSelector = "a img.item.lazy"
waitUntil = "networkidle"
