[tfactory]
title = "T팩토리"
url = "https://www.tfactory.co.kr/main/program"
entrySelector = "ul.list-program.wide.ani-obj li"
titleSelector = "p.tit"
linkSelector = "a"
contentSelector = "p.subtext"
imageSelector = "div.thumb img"
waitUntil = "networkidle"
