[thehit]
title = "THE HIT"
url = "https://the-hit.co/"
entrySelector = "ul li.ServiceItemList_item__1PzdI"
titleSelector = "h2[class^='euiTitle euiTitle']"
linkSelector = "a"
imageSelector = "div.euiFlexItem.euiFlexItem--flexGrowZero.ServiceItem_ServiceItem__logo__24DVQ > img"
contentSelector = "p[class^='ServiceItem_ServiceItem__summary'"
waitUntil = "networkidle"
