[interview]
title = "Weverse Magazine ─ INTERVIEW"
url = "https://magazine.weverse.io/article/list?lang=ko&colca=1"
entrySelector = "section.sub_article_list.article_list.col1 div.article_item.typeA"
titleSelector = "div.dec a.tit"
linkSelector = "div.dec a"
contentSelector = "div.dec div.date"
imageSelector = "div.img > a > img"
waitUntil = "networkidle"
