[parkjy_naver]
title = "동아사이언스 박진영 심리학 칼럼니스트 ─ 네이버 뉴스"
url = "https://news.naver.com/main/hotissue/sectionList.naver?mid=hot&sid1=110&cid=1077376"
entrySelector = "ul.tmp_bx li.tmp.small2"
titleSelector = "dl.cnt dt.t a"
linkSelector = "dl > dt > a"
contentSelector = "dd.c"
imageSelector = "div.thumb a img"
dateSelector = "dl > dd.s > em"
dateFormat = "yyyy.MM.dd"
waitUntil = "networkidle"
onFail = "stale"
