[thehit]
title = "THE HIT"
url = "https://the-hit.co/"
entrySelector = "ul li.ServiceItemList_item__1PzdI"
titleSelector = "h2[class^='euiTitle euiTitle']"
linkSelector = "ul li.ServiceItemList_item__1PzdI a"
contentSelector = "p[class^='ServiceItem_ServiceItem__summary']"
waitUntil = "networkidle"
