[ranking_popular]
title = "다음 뉴스 ─ 랭킹 ─ 많이 본"
url = "https://news.daum.net/ranking/popular"
entrySelector = "ul.list_news2 li"
titleSelector = "strong.tit_thumb a.link_txt"
linkSelector = "strong a.link_txt"
contentSelector = "span.info_news"

[ranking_popular_xpath]
title = "다음 뉴스 ─ 랭킹 ─ 많이 본"
url = "https://news.daum.net/ranking/popular"
entrySelector = "//ul[@class='list_news2']/li[@data-tiara-layer='news_list']"
titleSelector = "//div[2]/strong/a"
linkSelector = "//div[2]/strong/a"
contentSelector = "//div[2]/strong/span[@class='info_news']"
