[press]
title = "팩트체크넷 ─ 언론사"
url = "https://factchecker.or.kr/fc_archives/press"
entrySelector = "//html/body/div[1]/main/div[2]/div[1]/ul/li"
titleSelector = "//div[2]/div[1]/div[1]/div[1]/a"
linkSelector = "//div[2]/div[1]/div[1]/div[1]/a"
contentSelector = "//div[2]/div[1]/div[1]/div[2]"
imageSelector = "div[2]/div[2]/a/img"
dateSelector = "//div[2]/div[1]/div[1]/div[3]/div"
dateFormat = " yyyy.MM.dd "
waitUntil = "networkidle"
onFail = "stale"
