[melonticket_yerinbaek]
title = "멜론 티켓 ─ 백예린"
url = "https://ticket.melon.com/artist/index.htm?artistId=698776"
entrySelector = "table.tbl.tbl_style02 tbody tr"
titleSelector = "span.show_title"
linkSelector = "span.show_title a"
contentSelector = "td.show_date"
imageSelector = "div.thumb_90x125.img a img"
waitUntil = "networkidle"
