[clubevans]
title = "클럽 에반스 ─ SCHEDULE"
url = "http://www.clubevans.com/bbs/board.php?bo_table=TODAYS_LIVE"
entrySelector = "center[id='G4_LIST'] table tr:nth-child(n+3) td"
titleSelector = "div:nth-child(2) a"
linkSelector = "div:nth-child(2) a"
waitUntil = "networkidle"
