[interpark_ticket_exhibition]
title = "인터파크 티켓 ─ 전시/행사 ─ 전시"
url = "http://ticket.interpark.com/TPGoodsList.asp?Ca=Eve&SubCa=Eve_O&tid4=Eve_O"
entrySelector = "div.stit tbody tr"
titleSelector = "span.fw_bold a"
linkSelector = "span.fw_bold a"
contentSelector = "td.Rkdate:nth-child(4)"
imageSelector = "td.RKthumb a img"
waitUntil = "networkidle"
