[top]
title = "네이버 공연 live beta ─ 하이라이트"
url = "https://live.naver.com/"
entrySelector = "div.video-box-area div.video-list div div.eg-flick-camera div.video-box.eg-flick-panel"
titleSelector = "p.sub-title.ellipsis2"
linkSelector = "a.video"
contentSelector = "p.date.ellipsis"
imageSelector = "img._lazyImage"
waitUntil = "networkidle"
