[snufactcheck_notice]
title = "SNU 팩트체크 ─ 공지사항"
url = "http://factcheck.snu.ac.kr/documents?doc_type=notice"
entrySelector = "table.notice_table tbody tr"
titleSelector = "td a"
linkSelector = "td:nth-child(1) > a"
contentSelector = "td:nth-child(2)"
