[figk]
title = "FIGK"
url = "https://figk.net/"
entrySelector = "div.styles_TextFIGKContainer__1iZw8-"
titleSelector = "div.styles_Title__2bpAt"
linkSelector = "div.styles_ToolBox__2vzTh > a"
contentSelector = "div.styles_TextFIGKContainer__1iZw8"
waitUntil = "networkidle"
