[funshop_funtenna]
title = "펀샵 ─ 펀테나"
url = "https://www.funshop.co.kr/Story/FuntennaList"
entrySelector = "ul[id='list'] li"
titleSelector = "dl dt"
linkSelector = "a"
contentSelector = "dd p.text"
dateSelector = "p.info2 span.data span:nth-child(2)"
dateFormat = "yyyy-MM-dd"
imageSelector = "a img.item.lazy"
waitForSelector= "ul[id='list'] li"
