[musinsa]
title = "무신사 ─ Raffle"
url = "https://www.musinsa.com/event/raffles?raffles_include_state=S"
entrySelector = "a.view"
titleSelector = "strong.tit"
linkSelector = "*"
contentSelector = "span.brand"
imageSelector = "img"
waitUntil = "networkidle"
