[sbsnews_fact]
title = "SBS뉴스 ─ 사실은"
url = "https://news.sbs.co.kr/news/fact.do"
entrySelector = "ul.type_thumb li"
titleSelector = "strong"
linkSelector = "a"
imageSelector = "span.thumb img"
contentSelector = "a.reporter"
waitUntil = "networkidle"
