[nate_news_idolhissue_blackpink]
title = "네이트 연예 ─ 아이돌24h ─ 스타 ─ 블랙핑크"
url = "https://news.nate.com/ent/idolHissue?hissueSq=9895&mid=e0608"
entrySelector = ""
titleSelector = "strong.tit"
linkSelector = "div.mlt02 a"
contentSelector = "span.medium"
imageSelector = "span.ib img"
waitUntil = "networkidle"
