[hani_seunghan]
title = "한겨레S ─ 이승한의 술탄 오브 더 티브이"
url = "https://www.hani.co.kr/arti/SERIES/508/"
entrySelector = "div.series-list-area ul.one-type li"
titleSelector = "a"
linkSelector = "a"
waitForSelector = ".one-type"
