[kakaotv_eanakim]
title = "kakaoTV ─ 톡이나 할까?"
url = "https://tv.kakao.com/channel/3647846/video"
entrySelector = "ul.list_vertical li"
titleSelector = "strong.tit_item"
linkSelector = "a"
contentSelector = "span.mark_play"
imageSelector = "span.thumb_box img.thumb_img"
