[kbsnews_factcheckk]
title = "KBS 뉴스 ─ 팩트체크K"
url = "https://news.kbs.co.kr/news/list.do?mcd=1032"
entrySelector = "ul.list-type.list-thumb li"
titleSelector = "em.tit"
linkSelector = "a"
contentSelector = "span.script"
imageSelector = "span.img-center img"
waitUntil = "networkidle"
