[media]
title = "빵야 TV ─ 전체 영상"
url = "https://www.bbangyatv.com/media"
entrySelector = "div.row div[class='px-1 px-md-6 pt-5 pb-0 col-sm-6 col-md-4 col-lg-3 col-12']"
titleSelector = "div[class^='v-card__subtitle']"
linkSelector = "a"
waitForSelector = "div[class^='v-card__subtitle']"
onFail = "stale"
