[khan_flatflat38]
title = "경향신문 ─ 플랫"
url = "http://www.khan.co.kr/reporter_article.html?id=584"
entrySelector = "ul.list_df li"
titleSelector = "strong.tit_thumb.line_clamp3"
linkSelector = "a.link_cont"
contentSelector = "span.lead"
dateFormat =  "span.info_area span.byline em.letter"
imageSelector = "img.thumb_g"
waitUntil = "networkidle"
