[default]
timeout = 180

[premovie_theater_y]
title = "test"
url = "https://movie.daum.net/premovie/theater?flag=Y"
entrySelector = "ol.list_movieranking.aniposter_movie li"
titleSelector = "strong.tit_item a"
linkSelector = "strong.tit_item a"
waitForSelector = "ol.list_movieranking.aniposter_movie"
