[wwit]
title = "WWIT"
url = "https://wwit.design/"
entrySelector = "div.c-post-card"
titleSelector = "h2.c-post-card__title"
linkSelector = "h2 a.c-post-card__title-link"
contentSelector = "a.c-post-card__image-link"
imageSelector = "a.c-post-card__image-link img.c-post-card__image.js-fadein.is-inview"
waitUntil = "networkidle"
