[kobis_Daily]
title = "KOBIS ─ 일별 박스오피스"
url = "https://www.kobis.or.kr/kobis/mobile/main/findDailyBoxOfficeList.do"
entrySelector = "ul.list_mvie li"
titleSelector = "strong.tit.ellip"
linkSelector = "a"
contentSelector = "div.desc"
imageSelector = "span.thumb.boxofimg img"
waitUntil = "networkidle"
