[cine21_media_cover_photo]
title = "씨네21 ─ 멀티미디어 ─ 커버 ─ 사진"
url = "http://www.cine21.com/media/cover/photo"
entrySelector = "ul.coverdata li"
titleSelector = "div.tit_box p.ho_num"
linkSelector = "a.cover_image"
contentSelector = "div.tit_box p.date"
imageSelector = "img.thumb"
waitUntil = "networkidle"
