[cine21_notice]
title = "씨네21 ─ 공지사항"
url = "http://www.cine21.com/misc/cs/notice_list/"
entrySelector = "table.tb_list tr:nth-child(n+4)"
titleSelector = "td.subject a"
linkSelector = "td.subject a"
contentSelector = "td:nth-child(1)"
dataSelector = "td:nth-child(3)"
dateFormat = "yyyy-MM-dd"
waitUntil = "networkidle"

[cine21_review_E20041252]
title = "씨네21 ─ 리뷰 ─ 박평식"
url = "http://m.cine21.com/movie/review/cine21_view/?pre_code=E20041252"
entrySelector = "ul.expert_review li"
titleSelector = "div.title"
linkSelector = "div.title a"
contentSelector = "div.info > div span.num, div.review_txt"
imageSelector = "div.thub_img a img"
waitForSelector = ".expert_review"
onFail = "stale"

[cine21_review_E20041283]
title = "씨네21 ─ 리뷰 ─ 이동진"
url = "http://m.cine21.com/movie/review/cine21_view/?pre_code=E20041283"
entrySelector = "ul.expert_review li"
titleSelector = "div.title"
linkSelector = "div.title a"
contentSelector = "div.info"
imageSelector = "div.thub_img a img"
waitForSelector = ".expert_review"
onFail = "stale"
