[interview]
title = "POCLANOS ─ Interview"
url = "https://poclanos.com/category/interview/"
entrySelector = "article[class^='post']"
titleSelector = "h2.entry-title a"
linkSelector = "h2.entry-title a"
imageSelector = "a.post-thumbnail img"
waitUntil = "networkidle"
