[poclanos_interview]
title = "POCLANOS ─ Interview"
url = "https://poclanos.com/articles/"
entrySelector = "div.article-group.interview.content-current div.append-only-list div.single-article"
titleSelector = "h2.single-title"
linkSelector = "a"
imageSelector = "a span img"
waitUntil = "networkidle"
