[bookjournalism]
title = "북저널리즘"
url = "https://www.bookjournalism.com/books"
entrySelector = "div.item"
titleSelector = "span.summary"
linkSelector = "a.link-inner"
contentSelector = "span.post-title"
imageSelector = "span.cover"
waitUntil = "networkidle"
