[onstage]
title = "VIBE ─ 온스테이지"
url = "https://vibe.naver.com/onstage/season/2"
entrySelector = "ul.list li.item"
titleSelector = "strong.item_title"
linkSelector = "a.link_textarea"
contentSelector = "a p.desc"
waitForSelector = ".section_onstages"
