[folin]
title = "폴인"
url = "https://www.folin.co/story"
entrySelector = "//html/body/div[1]/div/article/section[2]/div/div/div[1]/ul/li"
titleSelector = "//a/div/h3"
linkSelector = "//a/@href"
contentSelector = "//a/div[2]/ul[1]"
waitUntil = "networkidle"
