[ticket_csoon_hot]
title = "멜론티켓 ─ 티켓오픈소식 ─ HOT 공연 오픈 소식"
url = "https://ticket.melon.com/csoon/index.htm#orderType=0&pageIndex=1&schGcode=GENRE_ALL&schText=&schDt="
entrySelector = "//html/body/div/div/div/div/div/div/div/div/div/ul/li/div[@class='cont']"
titleSelector = "//strong[@class='tit_consert']"
linkSelector = "//a[@class='thumb_160x225']"
contentSelector = "//span[@class='date']"
imageSelector = "//a/span[@class='img']/img"
waitUntil = "networkidle"
