[yes24livehall]
title = "예스24 라이브홀"
url = "https://yes24livehall.com/ko/show/list.php"
entrySelector = "div.shows"
titleSelector = "a.title"
linkSelector = "a"
contentSelector = "a.datetime"
imageSelector = "a.poster img"
waitUntil = "networkidle"
