[uppity_news]
title = "어피티 ─ 뉴스"
url = "https://uppity.co.kr/news"
entrySelector = "ul.li_body.holder"
titleSelector = "a.list_text_title._fade_link span"
linkSelector = "a.list_text_title._fade_link"
contentSelector = "li.category.hidden-xs a._fade_link em"
waitUntil = "networkidle"
