[event]
title = "네이버쇼핑 ─ 아트윈도 ─ 테마"
url = "https://shopping.naver.com/art/event"
entrySelector = "ul.XNP0X_c-6J li"
titleSelector = "a strong"
linkSelector = "a"
contentSelector = "p.S7nFgeJfh8"
imageSelector = "div img"
waitUntil = "networkidle"
