[channela_factman]
title = "채널A ─ 팩트맨"
url = "http://www.ichannela.com/news/template/program_news.do?cateCode=&subCateCode=000500&type=03&menuIndex=3&seqIndex=0&searchDate=&realCateCode=00050021"
entrySelector = "ul.newslist-type-thum2 li"
titleSelector = "span.top span.subject"
linkSelector = "a"
imageSelector = "span.thumArea img.thum"
waitUntil = "networkidle"
